@echo off
cd /d "d:\AI Book and Content Writer\book_automation_mcp"

powershell -Command "Get-Content 'drafts\chapter3_community_health_education.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter4_evidence_based_medicine.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter5_maternal_health_surveillance.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter6_national_vector_borne_disease_control.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter7_tb_control_program_rntcp.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter8_national_aids_control_program.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter9_health_information_systems_surveillance.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter10_noncommunicable_disease_surveillance.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter11_universal_immunization_programme.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter12_safe_motherhood_reproductive_health.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter13_maternal_nutrition_micronutrient_supplementation.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter14_child_health_surveillance_growth_monitoring.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter15_health_systems_organization_india.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter16_research_methodology_and_biostatistics.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter17_occupational_health_workplace_hazards.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter18_industrial_toxicology_risk_assessment.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter19_water_sanitation_hygiene_wash.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter20_climate_change_health_impacts.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter21_national_nutrition_programs_poshan_abhiyan.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter22_food_safety_adulteration_prevention.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter23_anemia_prevention_women_children.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter24_disaster_management_humanitarian_aid.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter25_health_policy_formulation_advocacy.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter26_cbme_curriculum_implementation.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter27_advanced_epidemiology.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter28_bioinformatics_public_health.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter29_e_governance_health_systems.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter30_health_informatics.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter31_phenomenology_studies.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter32_qualitative_research_methods.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter33_mixed_methods_approaches.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter34_participatory_epidemiology.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter35_systems_thinking_public_health.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter36_innovation_primary_healthcare.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter37_accreditation_systems.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter38_knowledge_management.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter39_cultural_competency_global_health.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter40_indigenous_medicine_integration.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter41_universal_basic_income_health_impacts.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter42_precision_public_health.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter43_sustainable_development_goals_monitoring.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter44_planetary_health.md' | Add-Content 'export\book\community_medicine_cbme.md'"
powershell -Command "Get-Content 'drafts\chapter45_circular_health_systems.md' | Add-Content 'export\book\community_medicine_cbme.md'"

echo All chapters appended successfully!
